version: '3'
services:
  envoy:
    build:
      context: ./envoy
      dockerfile: envoy-local.Dockerfile
    ports:
      - "8080:8080"
      - "9901:9901"
    extra_hosts:
      - "host.docker.internal:host-gateway"
